language: cpp
sudo: required
dist: trusty
os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake g++ libglm-dev libglew-dev libboost-all-dev freeglut3-dev libsdl2-image-dev libsdl2-dev wget default-jre unzip doxygen graphviz

script:
  - g++ --version
  - clang++ --version
  - cd build/
  - cmake ../src
  - make -j2
  - SpheresTest/SpheresTest
  - cd ..
  - doxygen spheresDoxygenDocs

